### ISSUE TITLE
Preview & debug UI for the browser

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-chrome-inspector#1]
As discussed in mint-metrics/mojito-js-delivery#11, I think a preview tool may help with general visibility of tests running on the site and debugging what's live.

I wrote a small bookmarklet to do this: 

```
javascript:(function()%7BMojito.addTest(%7Bid%3A%22preview%22%2Cname%3A%22Mojito%20preview%22%2Cstate%3A%22live%22%2CdivertTo%3A%221%22%2CsampleRate%3A1%2Ctrigger%3Afunction(e)%7BMojito.utils.domReady(function()%7BsetTimeout(e.activate%2C1e3)%7D)%7D%2Crecipes%3A%7B0%3A%7Bname%3A%22control%22%7D%2C1%3A%7Bname%3A%22treatment%22%2Cjs%3Afunction(e)%7Bvar%20t%3Ddocument.createElement(%22div%22)%3Bt.id%3D%22mojitoPreview%22%2Ct.innerHTML%3D'%20%20%20%20%20%20%20%20%3Cimg%20class%3D%22mjo-logo%22%20src%3D%22https%3A%2F%2Fmojito.mx%2Fimg%2Flogo.png%22%20height%3D%2240px%22%20width%3D%2279px%22%3E%20%20%20%20%20%20%20%20%3Cspan%20class%3D%22mjo-close%22%3E%3C%2Fspan%3E%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22mjo-tests%22%3E%3C%2Fdiv%3E%20%20%20%20%20%20%20%20'%2Ct.querySelector(%22.mjo-close%22).addEventListener(%22click%22%2Cfunction(e)%7Bdocument.getElementById(%22mojitoPreview%22).remove()%7D)%3Bvar%20o%3DObject.keys(Mojito.testObjects)%2Ca%3D%22%22%3Bo.reverse()%2Co.sort(function(e%2Ct)%7Breturn%20e%3DMojito.testObjects%5Be%5D%2Ct%3DMojito.testObjects%5Bt%5D%2Ce%3De.activated%3F1%3A%22live%22%3D%3D%3De.options.state%3F0%3A-1%2C(t%3Dt.activated%3F1%3A%22live%22%3D%3D%3Dt.options.state%3F0%3A-1)-e%7D)%3Bfor(var%20i%3D0%3Bi%3Co.length%3Bi%2B%2B)%7Bvar%20n%3D(e%3DMojito.testObjects%5Bo%5Bi%5D%5D).chosenRecipe%3F'%3Cspan%20class%3D%22mjo-recipe%22%3E'%2Be.chosenRecipe.name%2B%22%3C%2Fspan%3E%22%3A%22%22%3Ba%2B%3D'%3Cdiv%20class%3D%22mjo-wave%22%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20class%3D%22mjo-state%20mjo-state-'%2B(e.activated%3Fe.options.divertTo%3F%22divert%22%3A%22active%22%3A%22live%22%3D%3D%3De.options.state%3F%22inactive%22%3A%22staging%22)%2B'%22%3E%3C%2Fspan%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cspan%20class%3D%22mjo-wave-name%22%3E'%2Be.options.name%2B%22%3C%2Fspan%3E%22%2Bn%2B%22%3C%2Fdiv%3E%22%7Dt.querySelector(%22.mjo-tests%22).innerHTML%3Da%2Cdocument.body.appendChild(t)%7D%2Ccss%3A%22.mjo-wave%7Bwidth%3A200px%3Bdisplay%3Ainline-block%3Bpadding%3A5px%3Bvertical-align%3Amiddle%3Btext-overflow%3Aclip%3Boverflow%3Ahidden%3Bmargin%3A5px%3Bborder-radius%3A3px%203px%203px%203px%3Bbox-shadow%3A4px%204px%208px%200%20%23eee%3Bheight%3A55px%7D.mjo-recipe%7Bdisplay%3Ablock%3Bpadding-left%3A25px%7D.mjo-close%7Bcursor%3Apointer%3Bbackground%3Aurl(data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPD94bWwgdmVyc2lvbj0iMS4wIiA%2FPjxzdmcgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgNTEyIDUxMiIgaGVpZ2h0PSI1MTJweCIgaWQ9IkxheWVyXzEiIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDUxMiA1MTIiIHdpZHRoPSI1MTJweCIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI%2BPGc%2BPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgc3Ryb2tlLXdpZHRoPSIxMCIgeDE9IjMwOS42IiB4Mj0iMjAyLjQiIHkxPSIyMDIuNCIgeTI9IjMwOS42Ii8%2BPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS1taXRlcmxpbWl0PSIxMCIgc3Ryb2tlLXdpZHRoPSIxMCIgeDE9IjMwOS42IiB4Mj0iMjAyLjQiIHkxPSIzMDkuNiIgeTI9IjIwMi40Ii8%2BPC9nPjwvc3ZnPg%3D%3D)%3Bbackground-size%3Acontain%3Bwidth%3A40px%3Bheight%3A40px%3Bfloat%3Aright%7D.mjo-wave-name%7Bvertical-align%3Atop%7D.mjo-state%7Bwidth%3A16px%3Bheight%3A16px%3Bdisplay%3Ainline-block%7D.mjo-state-inactive%7Bbackground%3Aurl(%2F%2Fd1xafqim8ep2fx.cloudfront.net%2Fassets%2Fmojito-preview%2Finactive.svg)%3Bbackground-size%3Acontain%7D.mjo-state-divert%7Bbackground%3Aurl(%2F%2Fd1xafqim8ep2fx.cloudfront.net%2Fassets%2Fmojito-preview%2Fdivert.svg)%3Bbackground-size%3A100%25%20100%25%7D.mjo-state-active%7Bbackground%3Aurl(%2F%2Fd1xafqim8ep2fx.cloudfront.net%2Fassets%2Fmojito-preview%2Factive.svg)%3Bbackground-size%3Acontain%7D.mjo-state-staging%7Bbackground%3Aurl(%2F%2Fd1xafqim8ep2fx.cloudfront.net%2Fassets%2Fmojito-preview%2Fstaging.svg)%3Bbackground-size%3Acontain%7D.mjo-tests%7Boverflow-x%3Ascroll%3Boverflow-y%3Ahidden%3Bwhite-space%3Anowrap%3Bheight%3A60px%7D%23mojitoPreview%7Bheight%3A100px%3Bwidth%3A90%25%3Bmax-width%3A400px%3Bposition%3Afixed%3Bbottom%3A10px%3Bright%3A5%25%3Bbackground%3A%23fff%3Bz-index%3A9999%3Bborder-radius%3A5px%205px%205px%205px%3Bbox-shadow%3A3px%204px%2015px%200%20%23555%7D%22%7D%7D%7D)%7D)()
```

But I think there's more work to be done on this, like:

 - Test activation button
 - Change assigned recipes
 - Test exit button
 - Adding the functionality to the container, but hosting it externally - i.e. keeping container weight to a minimum

By splitting this out into a new card, we can follow this more closely.

**Comment by kingo55** [comment]
@dapperdrop agreed - I think container size/name is just nice to have. Let's worry about that later.

**Comment by dapperdrop** [comment]
@allmywant would you mind working on this one when you have time?

**Comment by allmywant** [comment]
@dapperdrop 
Sure I will do.

**Comment by allmywant** [comment]
@dapperdrop @kingo55 
In the mockup, there is a "Refresh page to apply changes" section. I think it should be a click-able button and user needs to click it to refresh, correct?

I need 2 icons (display on the toobar of Chrome), one is for enabled state (Mojito is running in current tab), the other is for disabled state (Mojito isn' running in current tab), the icon size: w: 128, h: 128, png.

They're not urgent, so take your time and Happy New Year!

**Comment by dapperdrop** [comment]
@allmywant 

>In the mockup, there is a "Refresh page to apply changes" section. I think it should be a click-able button and user needs to click it to refresh, correct?

Yes this is correct.

> I need 2 icons (display on the toobar of Chrome), one is for enabled state (Mojito is running in current tab), the other is for disabled state (Mojito isn' running in current tab), the icon size: w: 128, h: 128, png.

Here are the icons:

![mojito_disabled_128x128](https://user-images.githubusercontent.com/48050512/71611544-e526f300-2bed-11ea-8032-6113ed285a1b.png)
![mojito_enabled_128x128](https://user-images.githubusercontent.com/48050512/71611545-e5bf8980-2bed-11ea-991e-18b88ec43b5d.png)

Hope they are OK to use.

Happy New Year to you as well David!

**Comment by allmywant** [comment]
@dapperdrop @kingo55 
The existension is almost ready, you can install it from Chrome store:
https://chrome.google.com/webstore/detail/mojito-chrome-inspector/pogeofjajfmbkkbkpddgjfnadkajidpl

I know the UI isn't good enough, we can improve it as needed.
Please let me know if you found any problems.

**Comment by kingo55** [comment]
Holy crap! This is awesome....

We have both installed it here @allmywant  - and just giving it a test.

**Comment by dapperdrop** [comment]
Amazing work @allmywant !

Giving it a test now and it works well. The interface is very clean!

I'm sure we'll find some tweaks here and there, but it's looking really fantastic so far!

**Comment by kingo55** [comment]
@allmywant @dapperdrop - agreed... I've been playing around with this and it's very slick. 

I think the refinements & UI updates can wait. What are the next steps with this before we release and share with Mojito users?

**Comment by allmywant** [comment]
@kingo55 
Now the extension is public published in Chrome store, so it's ready for anyone. So next steps might be: writting a better version of description for extension, more screenshots?

**Comment by dapperdrop** [comment]
@allmywant 

Just one tweak before we move forward and release: can we hard code the colours of all elements? It seems that "dark mode" browsing on Mac (you can toggle it in the Chrome console settings as well), makes the interface difficult to use.

![image](https://user-images.githubusercontent.com/48050512/72019997-e5468300-32be-11ea-821c-be4e2ac9920b.png)

**Comment by allmywant** [comment]
@dapperdrop 
Fixed. I have published to Chrome store and it is in pending review state, will let you know when it's approved.

**Comment by dapperdrop** [comment]
Nice work @allmywant - I'll close this issue and start some new ones for bugs/enhancements.

**Comment by allmywant** [comment]
@dapperdrop @kingo55 
Version 0.9.3 has been approved.
